name: Deploy to EC2

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH key to known_hosts
        run: |
          ssh-keyscan -t rsa -H ${{ secrets.SERVER_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }} # Checkout the specific tag
          fetch-depth: 0

      - name: Print tag reference
        run: |
          echo "Tag reference: ${{ github.ref }}"

      - name: Deploy to EC2
        run: |
          ssh -v -i ~/.ssh/id_rsa ubuntu@${{ secrets.SERVER_PUBLIC_IP }} 'bash -s' < ./Scripts/Script.sh ${{ github.ref }}
